# Generated by Django 2.2.12 on 2022-11-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='status',
            field=models.CharField(choices=[('OF', 'Offline'), ('ON', 'Online'), ('SR', 'Serving')], default='ON', max_length=2),
        ),
    ]
