# Generated by Django 2.2.12 on 2022-11-16 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_counter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketing.Customer'),
        ),
    ]
